from experiment_group import experiment_group
import agent
import generators

tests = []

meta_file_name = "meta.txt"
res_file_name = "results.txt"
meta_file = open(meta_file_name, 'w')
res_file = open(res_file_name, 'w')

#add column labels to files (these will be set up like a csv)
meta_file.write("ExpNum " + "AgentType " + "UtilType " + "GenType " + "Alpha " + "Voters " + "Candidates " + "Iterations " + "Experiments " + "Borda_borda " \
                   + "Borda_copeland " + "Borda_plurality " + "Borda_stv " + "Condorcet " + "Cond_borda " + "Cond_copeland " + "Cond_plurality " \
                   + "Cond_stv\n")

res_file.write("ExpNum " + "Iter " + "Borda " + "Cond ")

meta_file.close()
res_file.close()

tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 1))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 2))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 3))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 4))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 5))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 6))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 7))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 8))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 9))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 10))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 11))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 12))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 13))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 14))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 15))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 16))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 17))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 18))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 19))
tests.append(experiment_group(agent.BestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 20))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 21))
tests.append(experiment_group(agent.BestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 22))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 23))
tests.append(experiment_group(agent.BestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 24))

tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 25))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 26))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 27))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 28))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 29))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 30))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 31))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 32))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 33))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 34))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 35))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 36))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 37))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 38))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 39))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 40))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 41))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 42))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 43))
tests.append(experiment_group(agent.PragmatistAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 44))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 45))
tests.append(experiment_group(agent.PragmatistAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 46))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 47))
tests.append(experiment_group(agent.PragmatistAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 48))

tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 49))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 50))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 51))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 52))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 53))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 54))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 55))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 56))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 57))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 58))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 59))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 60))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 61))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 62))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 63))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 64))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 65))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 66))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 67))
tests.append(experiment_group(agent.LearningAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 68))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 69))
tests.append(experiment_group(agent.LearningAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 70))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 71))
tests.append(experiment_group(agent.LearningAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 72))

tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 73))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 74))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 75))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 76))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 77))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 78))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 79))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 80))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 81))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 82))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.impartial_culture, 100, 10, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 83))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.impartial_culture, 100, 3, 1000, 100, alpha = None, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 84))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 85))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 86))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 87))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 88))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 89))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 90))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 91))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.linear_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 92))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 10, 1000,100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 93))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.exp_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 94))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 10, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 95))
tests.append(experiment_group(agent.LearningBestResponseAgent, agent.log_util, generators.polya_eggenberger, 100, 3, 1000, 100, .5, write = True, meta_file = "meta.txt", results_file = "results.txt", exp_num = 96))